import { ThemeDefinition } from "../types/theme";

export const defaultThemes: Record<string, ThemeDefinition> = {
  paper: {
    id: "paper",
    name: "Paper",
    description: "Optimal for daytime reading with warm off-white background",
    colors: {
      bgPrimary: "#FAFAF8",
      bgSecondary: "#F5F5F3",
      bgTertiary: "#EFEFE8",
      textPrimary: "#1F1F1F",
      textSecondary: "#4A4A48",
      textMuted: "#6B6B68",
      border: "rgba(0, 0, 0, 0.08)",
      borderHover: "rgba(0, 0, 0, 0.12)",
      hover: "rgba(0, 0, 0, 0.04)",
      shadow: "0 1px 3px rgba(0, 0, 0, 0.05)",
      readerBg: "#FAFAF8",
      readerText: "#1F1F1F",
      readerSelection: "rgba(59, 130, 246, 0.15)",
      readerHighlight: "rgba(251, 191, 36, 0.25)",
      accent: "#3B82F6",
      success: "#10B981",
      warning: "#F59E0B",
      error: "#EF4444",
    },
    epubStyles: {
      body: {
        color: "#1F1F1F !important",
        background: "#FAFAF8 !important",
        "font-family": "'Lora', Georgia, serif",
        "line-height": "1.75",
        padding: "0 1rem",
        "-webkit-font-smoothing": "antialiased",
        "-moz-osx-font-smoothing": "grayscale",
      },
      p: {
        margin: "0 0 1.25rem 0",
        "text-align": "justify",
        hyphens: "auto",
        "-webkit-hyphens": "auto",
        "-moz-hyphens": "auto",
      },
      "h1, h2, h3, h4, h5, h6": {
        "font-family": "'Inter', sans-serif",
        "font-weight": "600",
        "line-height": "1.2",
        "margin-top": "2rem",
        "margin-bottom": "1rem",
        color: "#1F1F1F !important",
      },
      blockquote: {
        "border-left": "3px solid rgba(0, 0, 0, 0.1)",
        "padding-left": "1.5rem",
        "margin-left": "0",
        "font-style": "italic",
        color: "#4A4A48 !important",
      },
      img: {
        "max-width": "100%",
        height: "auto",
        display: "block",
        margin: "2rem auto",
        "border-radius": "0.5rem",
      },
      "::selection": {
        background: "rgba(59, 130, 246, 0.15) !important",
        color: "inherit !important",
      },
    },
    timeRange: { start: 6, end: 18 },
  },

  sepia: {
    id: "sepia",
    name: "Sepia",
    description: "Warm tones for evening reading, reduces blue light",
    colors: {
      bgPrimary: "#F4F1EA",
      bgSecondary: "#EBE6DC",
      bgTertiary: "#E2DCD0",
      textPrimary: "#2C2416",
      textSecondary: "#5C5142",
      textMuted: "#7A6E5F",
      border: "rgba(92, 81, 66, 0.15)",
      borderHover: "rgba(92, 81, 66, 0.25)",
      hover: "rgba(92, 81, 66, 0.08)",
      shadow: "0 1px 3px rgba(92, 81, 66, 0.1)",
      readerBg: "#F4F1EA",
      readerText: "#2C2416",
      readerSelection: "rgba(218, 165, 32, 0.2)",
      readerHighlight: "rgba(218, 165, 32, 0.25)",
      accent: "#8B7355",
      success: "#7C8471",
      warning: "#D4A574",
      error: "#B87F77",
    },
    epubStyles: {
      body: {
        color: "#2C2416 !important",
        background: "#F4F1EA !important",
        filter: "sepia(20%)",
        "font-family": "'Lora', Georgia, serif",
        "line-height": "1.75",
      },
      // ... similar to paper but with sepia colors
    },
    timeRange: { start: 18, end: 22 },
  },

  night: {
    id: "night",
    name: "Night",
    description: "Dark mode for low-light reading",
    colors: {
      bgPrimary: "#1E1E1E",
      bgSecondary: "#252525",
      bgTertiary: "#2A2A2A",
      textPrimary: "#E8E6E3",
      textSecondary: "#A8A6A3",
      textMuted: "#787673",
      border: "rgba(255, 255, 255, 0.1)",
      borderHover: "rgba(255, 255, 255, 0.15)",
      hover: "rgba(255, 255, 255, 0.05)",
      shadow: "0 1px 3px rgba(0, 0, 0, 0.3)",
      readerBg: "#1E1E1E",
      readerText: "#E8E6E3",
      readerSelection: "rgba(90, 159, 212, 0.3)",
      readerHighlight: "rgba(255, 235, 59, 0.25)",
      accent: "#5A9FD4",
      success: "#4ADE80",
      warning: "#FCD34D",
      error: "#F87171",
    },
    epubStyles: {
      body: {
        color: "#E8E6E3 !important",
        background: "#1E1E1E !important",
        "font-family": "'Inter', sans-serif", // Sans-serif easier in dark
        "font-weight": "425", // Slightly heavier
        "line-height": "1.8",
        "letter-spacing": "0.02em",
      },
      // ... dark mode specific styles
    },
    timeRange: { start: 22, end: 6 },
  },

  highContrast: {
    id: "highContrast",
    name: "High Contrast",
    description: "Maximum contrast for users with visual impairments",
    colors: {
      bgPrimary: "#FFFFFF",
      bgSecondary: "#F8F8F8",
      bgTertiary: "#F0F0F0",
      textPrimary: "#000000",
      textSecondary: "#2C2C2C",
      textMuted: "#4A4A4A",
      border: "rgba(0, 0, 0, 0.2)",
      borderHover: "rgba(0, 0, 0, 0.3)",
      hover: "rgba(0, 0, 0, 0.08)",
      shadow: "0 2px 4px rgba(0, 0, 0, 0.15)",
      readerBg: "#FFFFFF",
      readerText: "#000000",
      readerSelection: "rgba(0, 102, 204, 0.3)",
      readerHighlight: "rgba(255, 235, 59, 0.4)",
      accent: "#0066CC",
      success: "#008844",
      warning: "#CC6600",
      error: "#CC0000",
    },
    epubStyles: {
      body: {
        color: "#000000 !important",
        background: "#FFFFFF !important",
        "font-family": "'Inter', sans-serif",
        "font-weight": "500",
        "line-height": "1.8",
        "letter-spacing": "0.01em",
      },
      // ... high contrast specific
    },
  },
};
